# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: datastores.atomix.io
spec:
  group: atomix.io
  scope: Namespaced
  names:
    kind: DataStore
    listKind: DataStoreList
    plural: datastores
    singular: datastore
  versions:
    - name: v3beta3
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the store.
              type: object
              required:
                - driver
              properties:
                driver:
                  type: object
                  required:
                    - name
                    - version
                  properties:
                    name:
                      type: string
                    version:
                      type: string
                config:
                  description: |-
                    The configuration for the runtime driver.
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                podStatuses:
                  type: array
                  items:
                    type: object
                    required:
                      - name
                    properties:
                      name:
                        type: string
                      state:
                        type: string
                        default: Pending
                        enum:
                          - Pending
                          - Connecting
                          - Connected
                          - Configuring
                          - Disconnecting
                          - Disconnected
                      version:
                        type: string
