# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: storageprofiles.atomix.io
spec:
  group: atomix.io
  scope: Namespaced
  names:
    kind: StorageProfile
    listKind: StorageProfileList
    plural: storageprofiles
    singular: storageprofile
    shortNames:
      - profiles
      - profile
      - sp
  versions:
    - name: v3beta3
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            spec:
              description: |-
                The specification for the profile.
              type: object
              required:
                - bindings
              properties:
                proxy:
                  type: object
                  properties:
                    image:
                      type: string
                    imagePullPolicy:
                      type: string
                      enum:
                        - Never
                        - IfNotPresent
                        - Always
                    securityContext:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    config:
                      type: object
                      properties:
                        server:
                          type: object
                          properties:
                            readBufferSize:
                              type: integer
                              nullable: true
                            writeBufferSize:
                              type: integer
                              nullable: true
                            maxSendMsgSize:
                              type: string
                              nullable: true
                            maxRecvMsgSize:
                              type: string
                              nullable: true
                            numStreamWorkers:
                              type: integer
                              nullable: true
                            maxConcurrentStreams:
                              type: integer
                              nullable: true
                        logging:
                          type: object
                          properties:
                            loggers:
                              type: object
                              additionalProperties:
                                type: object
                                properties:
                                  level:
                                    type: string
                                    nullable: true
                                    enum:
                                      - debug
                                      - info
                                      - warn
                                      - error
                                      - fatal
                                      - panic
                                  output:
                                    type: object
                                    additionalProperties:
                                      type: object
                                      properties:
                                        sink:
                                          type: string
                                        level:
                                          type: string
                                          nullable: true
                                          enum:
                                            - debug
                                            - info
                                            - warn
                                            - error
                                            - fatal
                                            - panic
                            sinks:
                              type: object
                              additionalProperties:
                                type: object
                                properties:
                                  encoding:
                                    type: string
                                    nullable: true
                                    enum:
                                      - console
                                      - json
                                  stdout:
                                    type: object
                                  stderr:
                                    type: object
                                  file:
                                    type: object
                                    properties:
                                      path:
                                        type: string
                                    required:
                                      - path
                bindings:
                  type: array
                  items:
                    type: object
                    required:
                      - store
                    properties:
                      store:
                        type: object
                        required:
                          - name
                        properties:
                          namespace:
                            type: string
                          name:
                            type: string
                      priority:
                        type: integer
                        minimum: 0
                        default: 0
                      tags:
                        type: array
                        items:
                          type: string
                      services:
                        type: array
                        items:
                          type: object
                          required:
                            - name
                          properties:
                            name:
                              type: string
                            config:
                              type: object
                              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns: []