# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "atomix-runtime-controller.fullname" . }}
webhooks:
  - name: injector.proxy.atomix.io
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.namespace
          operator: NotIn
          values: ["kube-system"]
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [ "" ]
        apiVersions: [ "v1" ]
        resources: [ "pods" ]
        scope: Namespaced
    clientConfig:
      service:
        name: {{ template "atomix-runtime-controller.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /inject-proxy
    admissionReviewVersions: [ "v1beta1" ]
    sideEffects: None
    failurePolicy: Fail
    timeoutSeconds: 10