apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  labels:
    app: example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
        proxy.atomix.io/inject: "true"
        proxy.atomix.io/profile: example-profile
    spec:
      containers:
        - name: sleep
          image: alpine:latest
          command: ["/bin/sh", "-c", "--"]
          args: ["while true; do sleep 30; done;"]