# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: atomix-runtime
description: Umbrella chart for deploying Atomix runtime controllers
kubeVersion: ">=1.17.0"
type: application
version: 0.1.10
appVersion: v0.1.9
keywords:
- atomix
home: https://atomix.io
maintainers:
- name: Jordan Halterman
  email: jordan.halterman@intel.com
dependencies:
  - name: atomix-runtime-controller
    version: 1.6.8
    repository: https://charts.atomix.io
    alias: controller
  - name: atomix-consensus-controller
    version: 1.5.1
    repository: https://charts.atomix.io
    condition: storage.consensus.enabled
    alias: consensus-controller
  - name: atomix-shared-memory-controller
    version: 1.0.0
    repository: https://charts.atomix.io
    condition: storage.sharedMemory.enabled
    alias: shared-memory-controller
  - name: atomix-pod-memory-controller
    version: 1.0.0
    repository: https://charts.atomix.io
    condition: storage.podMemory.enabled
    alias: pod-memory-controller
